movie/urls.py
from django.urls import path 
from . import views

app_name = "movie"

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('accounts/', views.accounts, name='accounts'),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/', views.update, name='update'),
    path('logout/', views.logout, name='logout'),
    path('create/', views.create, name='create'),
    path('community/', views.community, name='community'),
    path('review_detail/<int:pk>/', views.review_detail, name='review_detail'),
    path('review_update/<int:pk>', views.review_update, name='review_update'),
    path('review_delete/<int:pk>', views.review_delete, name='review_delete'),
]

moviepjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

movie/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Review(models.Model):
    title = models.CharField(max_length=30) # 리뷰 제목
    content = models.TextField(null=False) # 리뷰 내용
    movie_name = models.CharField(max_length=30) # 영화 이름
    grade = models.DecimalField(max_digits=2, decimal_places=1) # 영화 평점
    created_at = models.DateTimeField(auto_now_add=True) # 리뷰 생성시간
    updated_at = models.DateTimeField(auto_now=True) # 리뷰 수정시간

movie/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django import forms
from .models import Review

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        # 제목, 내용, 이름, 평점을 사용자에게 입력받음 + 유효성 검사
        fields = ['title', 'content', 'movie_name', 'grade']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'content' : forms.Textarea(attrs={'class':'form-control', 'style': 'height: 100px;'}),
            'movie_name' : forms.TextInput(attrs={'class':'form-control'}),
            'grade' : forms.TextInput(attrs={'class':'form-control'}),
        }

movie/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from .forms import ReviewForm
from .models import Review



# Create your views here.
def index(request):
    return render(request, 'movie/index.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movie:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'movie/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movie:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'movie/login.html', context)

def accounts(request):
    accounts = get_user_model().objects.order_by('-pk')
    context = {
        'accounts': accounts
    }
    return render(request, 'movie/accounts.html', context)


def detail(request, pk):
  user = get_user_model().objects.get(pk=pk)
  context = {
    'user': user
    }
  return render(request, 'movie/detail.html', context)

@login_required(login_url='movie:login')
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movie:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'movie/update.html', context)

def logout(request):
  auth_logout(request)
  return redirect('movie:index')

@login_required(login_url='movie:login')
def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect('movie:community')
    else:        
        review_form = ReviewForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'movie/create.html', context=context)

def community(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews
    }
    return render(request, 'movie/community.html', context)

def review_detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        'review': review
    }
    return render(request, 'movie/review_detail.html', context)

@login_required(login_url='movie:login')
def review_update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect('movie:review_detail', review.pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        'review_form': review_form
    }
    return render(request, 'movie/review_update.html', context)

@login_required(login_url='movie:login')
def review_delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect('movie:community')

movie/templates/movie/accounts.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  <div class="col-lg-9 col-md-12 px-5 mb-3">
    <!-- 테이블 영역 -->
    <table class="table">
      <!-- 테이블 헤드 -->
      <thead class="table-light">
        <tr>
          <th scope="col">PK</th>
          <th scope="col">USER NAME</th>
          <th scope="col">EMAIL</th>
        </tr>
      </thead>
      <!-- 테이블 바디 -->
      <tbody class="table-group-divider">
        {% for account in accounts %}
          <tr>
            <th>{{ account.pk }}</th>
            <th>
              <a href="{% url 'movie:detail' account.pk %}">
                {{ account.username }}</a>
            </th>

            <th>{{ account.email }}</th>

          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock body %}

movie/templates/movie/community.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    a {
      text-decoration: none;
      color: inherit;
    }
  </style>
{% endblock %}

{% block body %}
  <!-- 게시판 영역 -->
  <section class="mx-5">
    <!-- 게시판 제목 -->
    <div class="text-center my-5 mx-5">
      <a href="{% url 'movie:community' %}">
        <h1>Community</h1>
      </a>
    </div>
    <!-- 게시판 내용 -->
    <div class="row">
      <!-- 테이블 헤더 -->
      <div class="col-lg-3 col-md-12 px-5 mb-3">
        <ul class="list-group">
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Boxoffice</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Movies</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Genres</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Actors</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-9 col-md-12 px-5 mb-3">
        <!-- 테이블 영역 -->
        <table class="table">
          <!-- 테이블 헤드 -->
          <thead class="table-light">
            <tr>
              <th scope="col">순번</th>
              <th scope="col">리뷰 제목</th>
              <th scope="col">영화 이름</th>
            </tr>
          </thead>
          <!-- 테이블 바디 -->
          <tbody class="table-group-divider">
            {% for review in reviews %}
              <tr>
                <th>{{ review.pk }}</th>
                <th>
                  <a href="{% url 'movie:review_detail' review.pk %}">{{ review.title }}</a>
                </th>
                <th>{{ review.movie_name }}</th>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="col-12">
          <form action="{% url 'movie:create' %}">
            <button class="btn btn-outline-primary">리뷰작성</button>
          </form>
        </div>
      </div>
    </div>
  </section>
  <nav class="mt-2 mb-2" aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="#">Previous</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </nav>

{% endblock %}

movie/templates/movie/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <div class="container mt-3">
    <h1>글쓰기</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {{ review_form.as_p }}
      <button type="submit" class="btn btn-outline-primary">추가</button>
    </form>
  </div>
{% endblock %}

movie/templates/movie/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  <div class="container">
    <h1 class="mt-3">상세 페이지</h1>
    <div class="mb-3 mt-3">
      <label for="userpk" class="form-label">순번</label>
      <textarea name='content' class="form-control" id="userpk" rows="3" disabled="disabled" readonly="readonly">{{ user.pk }}</textarea>
    </div>
    <div class="mb-3">
      <label for="username" class="form-label">유저명</label>
      <textarea name='content' class="form-control" id="username" rows="3" disabled="disabled" readonly="readonly">{{ user.username }}</textarea>
    </div>
    <div class="mb-3">
      <label for="useremail" class="form-label">이메일</label>
      <textarea name='content' class="form-control" id="useremail" rows="3" disabled="disabled" readonly="readonly">{{ user.email }}</textarea>
    </div>
    <div class="mt-2">
      <a href="{% url 'movie:update' %}">
        <button class="btn btn-outline-primary">수정하기</button>
      </a>
    </div>
  </div>
{% endblock body %}

movie/templates/movie/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <!-- carousel -->
  <div id="carouselExampleControls" class="carousel slide bg-dark" data-bs-ride="carousel">
    <!-- inner -->
    <div class="carousel-inner">
      <!-- 1 -->
      <div class="carousel-item active">
        <img src="{% static 'images/carousel4.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">세계의 영화를 한곳에.</h2>
          <p>모든 영화들이 이곳에 있습니다</p>
        </div>
      </div>
      <!-- 2 -->
      <div class="carousel-item">
        <img src="{% static 'images/carousel3.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">당신의 취향에 맞는<br>시리즈 추천.</h2>
          <p></p>
        </div>
      </div>
      <!-- 3 -->
      <div class="carousel-item">
        <img src="{% static 'images/carousel1.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">다양한 영화 리뷰를 하나로.</h2>
          <p>다양한 유저들과 소통하고 평점을 매겨보세요</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- 포스터 섹션 -->
  <section class="py-5 px-5">
    <div class="text-center mb-5">
      <h2 class="fw-bold">Boxoffice</h2>
    </div>
    <div class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-1 row-cols-xs-1 gx-4">
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/278-the-shawshank-redemption?language=ko"><img class="card-img-top" src="{% static 'images/movie1.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">쇼생크 탈출</h5>
            </div>
            <p class="d-flex justify-content-center mb-0">평점 : 9.88
            </p>
            <div class="d-flex justify-content-center text-warning mb-2">
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/207-dead-poets-society?language=ko"><img class="card-img-top" src="{% static 'images/movie2.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">죽은 시인의 사회</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.56
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/49026-the-dark-knight-rises?language=ko"><img class="card-img-top" src="{% static 'images/movie3.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">다크 나이트 라이즈</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.56
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/120467-the-grand-budapest-hotel?language=ko"><img class="card-img-top" src="{% static 'images/movie4.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">그랜드 부다페스트 호텔</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 8.71
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-half"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/152601-her?language=ko"><img class="card-img-top" src="{% static 'images/movie5.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">그녀</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 8.70
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-half"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/316029-the-greatest-showman?language=ko"><img class="card-img-top" src="{% static 'images/movie6.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">위대한 쇼맨</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.31
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

movie/templates/movie/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="container">
  <h1 class="mt-3">로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
    {% comment %} <button class="btn btn-outline-primary col-12">로그인</button> {% endcomment %}
  </form>
</div>
{% endblock %}

movie/templates/movie/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <form class="container mt-3">
    <h1>{{ review.title }}</h1>
    <span>작성시간 :
      {{ review.created_at }}
      | 수정시간 :
      {{ review.updated_at }}</span>
    <div class="mb-3 mt-3">
      <label for="reviewContent" class="form-label">내용</label>
      <textarea name='content' class="form-control" id="reviewContent" rows="3" disabled="disabled" readonly="readonly">{{ review.content }}</textarea>
    </div>
    <div class="mb-3">
      <label for="moviename" class="form-label">영화 제목</label>
      <textarea name='content' class="form-control" id="moviename" rows="3" disabled="disabled" readonly="readonly">{{ review.movie_name }}</textarea>
    </div>
    <div class="mb-3">
      <label for="reviewgrade" class="form-label">평점</label>
      <textarea name='content' class="form-control" id="reviewgrade" rows="3" disabled="disabled" readonly="readonly">{{ review.movie_name }}</textarea>
    </div>

    <div class="row">
      <div class="col">
        <a href="{% url 'movie:review_update' review.pk %}">
          <button type="button" class="btn btn-outline-primary">리뷰 수정</button>
        </a>

        <a href="{% url 'movie:review_delete' review.pk %}">
          <button type="button" class="btn btn-outline-danger">리뷰 삭제</button>
        </a>
      </div>
    </div>
  </form>
{% endblock %}

movie/templates/movie/review_update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <div class="container mt-3">
    <h1>수정하기</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {{ review_form.as_p }}
      <button type="submit" class="btn btn-outline-primary">수정</button>
    </form>
  </div>
{% endblock %}

movie/templates/movie/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  <div class="container">
    <h1 class="mt-3">회원가입</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-outline-primary">제출하기</button>
    </form>
  </div>
{% endblock body %}

movie/templates/movie/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<div class="container">
  <h1 class="mt-3">수정하기</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
    {% comment %} {% issoman %} {% endcomment %}
  </form>
</div>
{% endblock %}

moviepjt/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BobMovie</title>
    <style>
      @font-face {
        font-family: "NetflixSans";
        src: url("fonts/NetflixSans-Regular.woff2") format("woff2");
        font-weight: normal;
        font-style: normal;
      }

      * {
        font-family: 'NetflixSans';
      }

      .nav-logo {
        width: 5rem;
        object-fit: cover;
      }

      a {
        text-decoration: none;
        color: inherit;
      }
    </style>
    {% bootstrap_css %}
    {% block css %}
      <link rel="stylesheet" href="{% static 'css/movie.css' %}">
    {% endblock css %}

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="nav mx-1">
        <a href="{% url 'movie:index' %}"><img class="nav-logo mx-1" src="https://user-images.githubusercontent.com/66688033/193211411-15f19a4c-d81f-409c-955a-ec224c8671be.png"/></a>
      </div>
      <button class="navbar-toggler mx-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- 두 항목을 오른쪽으로 밀기 .me-auto -->
        <!-- .navbar-nav으로 full-height와 보다 가벼운 네비게이션(드롭다운을 위한 지원 포함)을 실현. -->
        <ul class="navbar-nav mb-2 mx-3 mb-lg-0 ms-lg-4 align-items-end">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'movie:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movie:community' %}">Community</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color:white;" href="{% url 'movie:detail' user.pk %}">{{ request.user }}님, 환영합니다.</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie:signup' %}">Join</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color:white;">로그인 해주세요</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block body %}{% endblock body %}
    <footer class="py-3 bg-dark col-12 position-fixed bottom-0">
      <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Web Bootstrap PROJ. by 최준혁</p>
      </div>
    </footer>
    {% bootstrap_javascript %}
  </body>

</html>